### ISSUE TITLE
FARMING - Mobile UI/UX fixes

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold_farming#72]
General:

- [ ] Navbar needs a bg as everything scrolls behind it it loses it's readability at times
- [x]  After clicking MORE in the navbar it's impossible on my phone to press community as it falls off the screen.

Homepage:

- [x]  Horizontal scrolling issue
- [x] In the news section logo's are being scaled without respecting proportions

Whypage:

- [x] Images are being cropped very weirdly (see globe image being chopped)

Techpage:

- [x] Horizontal Scrolling
- [x] Images are being cropped very weirdly (see zero-os/zero people)

3Nodepage:

- [x] horizontal scrolling

Tokenpage:

- [x] horizontal scrolling

Pre-registerpage:

- [x]  horizontal scrolling

Teampage:

- [x] horizontal scrolling
- [x] Can't tap filters as their too close to the navbar

Newsroom:

- [x] horizontal scrolling
- [x] Can't tap filters as their too close to the navbar

Blog:

- [x] horizontal scrolling
- [x] Can't tap filters as their too close to the navbar

**Comment by VonSub** [comment]
Will these items be crossed off before end of 2.5 sprint?

**Comment by ehab-hassan** [comment]
Navbar needs a bg as everything scrolls behind it it loses it's readability at times
![Threefold-Farming-Threefold-Farming (1)](https://user-images.githubusercontent.com/10484295/107957681-9c74f980-6fa9-11eb-87a1-a4ae1ead36fc.png)
there is white background it is not transparent also at black mood

**Comment by ehab-hassan** [comment]
fixed at local still waiting for staging to be update so we can test u can check it local for now

**Comment by Vilnite** [comment]
Transparent navbar wont work as then menu and icons will overlay content.
I'd say common sense is not to scroll navbar over text you're reading.

**Comment by Vilnite** [comment]
Looks like we can't update staging atm. That still needs to be setup according to branch changes (development & master).
I'll close this issue but please @VonSub check it when staging is updated and reopen if something is still missing.

**Comment by VonSub** [comment]
Verified now.
